name: Build Linux binary

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master" ]
  workflow_call:
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Type of build to execute'
        required: true
        default: 'Release'

jobs:
  build:
    name: Linux build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev
        sudo apt-get install -y libgl1-mesa-dev libglu1-mesa-dev
        sudo apt-get install -y build-essential cmake meson just

    - name: Setup build
      run: |
        meson setup --buildtype release build

    - name: Build
      run: |
        meson compile -C build

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: u7revisited
        path: build/U7Revisited
